[package]
name = "rocket_learning"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.2", features = ["json"] }
rocket_dyn_templates = { version = "0.1.0-rc.2", features = ["tera"] }
serde = "1.0"
serde_json = "1.0"

[profile.dev]
opt-level = 1

[profile-release]
opt-level = 3
