[default]
address = "0.0.0.0"
port = 7003
limits = { form = "1024 kB", json = "20 MiB" }
secret_key = "hPRYyVRiMyxpw5sBB1XeCMN1kFsDCqKvBi2QJxBVHQk="

[profil-release]
address = "0.0.0.0"
port = 7003
limits = { form = "1024 kB", json = "20 MiB" }
secret_key = "hPRYyVRiMyxpw5sBB1XeCMN1kFsDCqKvBi2QJxBVHQk="